import AnimatedText from '@/components/AnimatedText'
import HireMe from '@/components/HireMe'
import { LinkArrow } from '@/components/Icons'
import Layout from '@/components/Layout.'
import Head from 'next/head'
import Link from 'next/link'
import TransitionEffect from '@/components/TransitionEffect'

export default function Home() {
  return (
    <>
      <Head>
        <title>Alberto La Rosa</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className='w-5/12 flex flex-col items-center self-center lg:w-full lg:text-center'>
                <AnimatedText text="Engineer by training Product thinker by choice" className='!text-6xl !text-left
                xl:!text-5xl lg:!text-center lg:!text=6xl md:!text-5xl sm:!text-3xl
                '/>
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
                  Hi, I’m Alberto, a Data Engineer turned MBA and aspiring Product Manager.
                  I’m passionate about building data-driven products that solve real problems 
                  and create measurable impact. With 5+ years of experience designing analytics platforms 
                  and automation solutions, I now focus on bridging the gap between business strategy and 
                  technology to deliver products users love and companies trust.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="/resume_alberto_la_rosa.pdf" target={"_blank"}
                className="flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark

                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                hover:dark:border-light md:p-2 md:px-4 md:text-base
                "
                download={true}
                >Resume <LinkArrow className={"w-6 ml-1"}/>
                
                </Link>
                <Link href="mailto:alarosainfante@gmail.com" target={"_blank"}
                className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />
      </main>
    </>
  )
}
